### ISSUE TITLE
Why always loading EthernetWebServer and LittleFS?

### ISSUE THREAD

**Issue by CNSNGopenSourceProjects** [khoih-prog/Ethernet_Generic#24]
I did a small implementation using Generic RP2040 + W5500 to access the NTP servers and the IoT Cloud (AWS) using MQTT.
Why the libraries EthernetWebServer and LittleFS are always included?
Is there someway to not do it?

Best regards,

Fernando Camargo
mailto:fernando.camargo@conseng.com.br

**Comment by khoih-prog** [comment]
Please don't post **nonsense and time-wasting** issue, without the [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example)

> Why the libraries EthernetWebServer and LittleFS are always included?

You have to understand and show **where / how** that can happen. By this library or somewhere else ???

Only post here in the issue if you can prove there is a bug of or enhancement for this library. Otherwise, post on [**Discussions Q/A section**](https://github.com/khoih-prog/Ethernet_Generic/discussions)
